title:            LOCKDOWN
tagline:          LIFE
description: 
# An awesome quote for your website
quote:  
canonical: Amp0ule.github.io

#Comment out the below line when pushing to gh-pages
#url: http://10.42.0.1/_site 
#For local development only. Comment it out.
#file_end: .html
#url: http://localhost:4000

# Owner/author information
owner:
  name:           Amp0ule
  avatar:         
  bio:            
  email:          nicolas.magnani@epita.fr
  twitter:        
  github:         Amp0ule
  instagram:      
  dribbble:
  googleplus:        
  disqus:         
  location:       

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title : Read
    url: /read/
  - title: Objectives
    url: /objectives
  - title: Review 
    url: /review


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

sass:
    sass_dir: _sass
    style: :compressed


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
